feat: use latest tmux sessionizer

diff --git a/bin/.local/scripts/tmux-sessionizer b/bin/.local/scripts/tmux-sessionizer
--- a/bin/.local/scripts/tmux-sessionizer
+++ b/bin/.local/scripts/tmux-sessionizer
@@ -1,66 +1,172 @@
 #!/usr/bin/env bash
+CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/tmux-sessionizer"
+CONFIG_FILE="$CONFIG_DIR/tmux-sessionizer.conf"
 
-# directories where their child directories are individual projects
-workspaces=(
-    "$HOME/workspace/nathan-logan"
-    "$HOME/workspace/nathan-logan/grapevine"
-    "$HOME/workspace/nathan-logan/elitefibreoptics"
-    "$HOME/workspace/struolabs"
-    "$HOME/workspace/picklebet"
-    "$HOME/.dotfiles"
-)
+# config file example
+# ------------------------
+# # file: ~/.config/tmux-sessionizer/tmux-sessionizer.conf
+# # If set this override the default TS_SEARCH_PATHS (~/ ~/personal ~/personal/dev/env/.config)
+# TS_SEARCH_PATHS=(~/)
+# # If set this add additional search paths to the default TS_SEARCH_PATHS
+# # The number prefix is the depth for the Path [OPTIONAL]
+# TS_EXTRA_SEARCH_PATHS=(~/ghq:3 ~/Git:3 ~/.config:2)
+# # if set this override the TS_MAX_DEPTH (1)
+# TS_MAX_DEPTH=2
+# TS_WORKSPACE_COMMAND=<cmd>
+# ------------------------
 
-# these are projects that should be shown in the list, but not their child directories
-projects=(
-    "$HOME/workspace/picklebet/skrilla/client/site"
-    "$HOME/workspace/nathan-logan/grapevine/web/apps/admin"
-    "$HOME/workspace/nathan-logan/grapevine/web/apps/portal"
-    "$HOME/workspace/nathan-logan/grapevine/web/packages/ui"
-    "$HOME/workspace/notes"
-    "$HOME/.dotfiles/.config/nvim"
-)
+# test if the config file exists
+if [[ -f "$CONFIG_FILE" ]]; then
+    # shellcheck source=/dev/null
+    source "$CONFIG_FILE"
+fi
+
+workspace=""
+VERSION="0.1.0"
+
+while [[ "$#" -gt 0 ]]; do
+    case "$1" in
+    -h | --help)
+        echo "Usage: tmux-sessionizer [OPTIONS] [SEARCH_PATH]"
+        echo "Options:"
+        echo "  -h, --help             Display this help message"
+        echo "  -w, --workspace <name> Namespace to the sessionizer.  Empty by default.  --workspace one is equivalent to empty"
+        exit 0
+        ;;
+    -w | --workspace)
+        workspace="$2"
+        if [[ -z $workspace ]]; then
+            echo "Workspace name cannot be empty"
+            exit 1
+        fi
+
+        if [[ -z $TS_WORKSPACE_COMMAND ]]; then
+            echo "TS_WORKSPACE_COMMAND is not set.  Must have a command set to run when switching to a workspace"
+            exit 1
+        fi
+
+        shift
+        ;;
+    -v | --version)
+        echo "tmux-sessionizer version $VERSION"
+        exit 0
+        ;;
+    *)
+        workspace="$1"
+        ;;
+    esac
+    shift
+done
+
+sanity_check() {
+    if ! command -v tmux &>/dev/null; then
+        echo "tmux is not installed. Please install it first."
+        exit 1
+    fi
+
+    if ! command -v fzf &>/dev/null; then
+        echo "fzf is not installed. Please install it first."
+        exit 1
+    fi
+}
+
+switch_to() {
+    if [[ -z $TMUX ]]; then
+        tmux attach-session -t "$1"
+    else
+        tmux switch-client -t "$1"
+    fi
+}
+
+has_session() {
+    tmux list-sessions | grep -q "^$1:"
+}
+
+hydrate() {
+    if [[ ! -z $workspace ]]; then
+        echo "Hydrating workspace: $workspace"
+        tmux send-keys -t "$1" "$TS_WORKSPACE_COMMAND" c-M
+    elif [ -f "$2/.tmux-sessionizer" ]; then
+        echo "Hydrating session: $2"
+        tmux send-keys -t "$1" "source $2/.tmux-sessionizer" c-M
+    elif [ -f "$HOME/.tmux-sessionizer" ]; then
+        echo "Hydrating session: $HOME/.tmux-sessionizer"
+        tmux send-keys -t "$1" "source $HOME/.tmux-sessionizer" c-M
+    fi
+}
+
+sanity_check
+
+# if TS_SEARCH_PATHS is not set use default
+[[ -n "$TS_SEARCH_PATHS" ]] || TS_SEARCH_PATHS=(~/ ~/personal ~/personal/dev/env/.config)
+
+# Add any extra search paths to the TS_SEARCH_PATHS array
+# e.g : EXTRA_SEARCH_PATHS=("$HOME/extra1:4" "$HOME/extra2")
+# note : Path can be suffixed with :number to limit or extend the depth of the search for the Path
+
+if [[ ${#TS_EXTRA_SEARCH_PATHS[@]} -gt 0 ]]; then
+    TS_SEARCH_PATHS+=("${TS_EXTRA_SEARCH_PATHS[@]}")
+fi
+
+# utility function to find directories
+find_dirs() {
+    # list TMUX sessions
+    if [[ -n "${TMUX}" ]]; then
+        current_session=$(tmux display-message -p '#S')
+        tmux list-sessions -F "[TMUX] #{session_name}" 2>/dev/null | grep -vFx "[TMUX] $current_session"
+    else
+        tmux list-sessions -F "[TMUX] #{session_name}" 2>/dev/null
+    fi
+
+    # note: TS_SEARCH_PATHS is an array of paths to search for directories
+    # if the path ends with :number, it will search for directories with a max depth of number ;)
+    # if there is no number, it will search for directories with a max depth defined by TS_MAX_DEPTH or 1 if not set
+    for entry in "${TS_SEARCH_PATHS[@]}"; do
+        # Check if entry as :number as suffix then adapt the maxdepth parameter
+        if [[ "$entry" =~ ^([^:]+):([0-9]+)$ ]]; then
+            path="${BASH_REMATCH[1]}"
+            depth="${BASH_REMATCH[2]}"
+        else
+            path="$entry"
+        fi
+
+        [[ -d "$path" ]] && find "$path" -mindepth 1 -maxdepth "${depth:-${TS_MAX_DEPTH:-1}}" -path '*/.git' -prune -o -type d -print
+    done
+}
 
 if [[ $# -eq 1 ]]; then
-    selected=$1
+    selected="$1"
+elif [[ ! -z $workspace ]]; then
+    selected=$(pwd)
 else
-    directories=()
-
-    # populate direct project directories first
-    for project in "${projects[@]}"; do
-        # since this is a direct link to a project folder, we should check if it exists
-        if test -d $project; then
-            directories+=("$project")
-        fi
-    done
-
-    for workspace in "${workspaces[@]}"; do
-        # check if the workspace directory exists
-        if test -d $workspace; then
-            directories+=("$(find "${workspace}" -mindepth 1 -maxdepth 1 -type d)")
-        fi
-    done
-
-    selected=$(printf "%s\n" "${directories[@]}" | fzf)
+    selected=$(find_dirs | fzf)
 fi
 
 if [[ -z $selected ]]; then
     exit 0
 fi
 
+if [[ "$selected" =~ ^\[TMUX\]\ (.+)$ ]]; then
+    selected="${BASH_REMATCH[1]}"
+fi
+
 selected_name=$(basename "$selected" | tr . _)
 tmux_running=$(pgrep tmux)
 
+if [[ ! -z $workspace ]]; then
+    if [[ $workspace != "one" ]]; then
+        selected_name="${selected_name}_${workspace}"
+    fi
+fi
+
 if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
-    tmux new-session -s $selected_name -n $selected_name -c $selected
-    exit 0
+    tmux new-session -ds "$selected_name" -c "$selected"
+    hydrate "$selected_name" "$selected"
 fi
 
-if ! tmux has-session -t=$selected_name 2>/dev/null; then
-    tmux new-session -ds $selected_name -n $selected_name -c $selected
+if ! has_session "$selected_name"; then
+    tmux new-session -ds "$selected_name" -c "$selected"
+    hydrate "$selected_name" "$selected"
 fi
 
-if [[ -z $TMUX ]]; then
-    tmux attach -t $selected_name
-else
-    tmux switch-client -t $selected_name
-fi
+switch_to "$selected_name"
